apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplychain
  template:
    metadata:
      labels:
        app: supplychain
    spec:
      containers:
      - name: app
        image: mehrajpatel/supplychain-demo@sha256:be30ea5fcc7f61bf8353cbaf5b2972308d2e5cbdbabf505843e9e446b0138c2d
